version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/data:/code/data   # Mount data directory within container
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
